### ISSUE TITLE
Npm module not found by typescript "node" resolution strategy

### ISSUE THREAD

**Issue by stgatilov** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#1]
Currently npm package is named "strongly-typed-events", but the definitions file in it is named "StronglyTypedEvents.d.ts". As a result typescript (version 1.8.10) cannot find the module after "npm install strongly-typed-events":
`Error TS2307: Cannot find module 'strongly-typed-events
`
According to node resolution strategy described [here](https://www.typescriptlang.org/docs/handbook/module-resolution.html), this is expected behavior of typescript.

I see two ways of fixing it:
1. Rename StronglyTypedEvents.ts to strongly-typed-events.ts (and do the same for generated files).
2. Add  "typings": "StronglyTypedEvents.d.ts" line to package.json of npm module.

**Comment by KeesCBakker** [comment]
Will solution 1 work on all platforms? Sounds like the best way to go.

**Comment by KeesCBakker** [comment]
Should be resolved now. Can you check if the latest changes solves this problem?

**Comment by KeesCBakker** [comment]
Any luck?
