### ISSUE TITLE
Build failing on v2.1.2

### ISSUE THREAD

**Issue by scottmbulloch** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#104]
Latest version of strongly-typed-events package has a dependency of `ste-core@^2.1.1` which does not appear to be published yet, the latest is `2.0.9`.

https://www.npmjs.com/package/ste-core

This is causing build to fail, I found the exact same issue in your Travis CI build #603.
https://travis-ci.org/github/KeesCBakker/Strongly-Typed-Events-for-TypeScript/builds/761263757

**Comment by KeesCBakker** [comment]
Should be fixed today in 2.1.3, can you check?

**Comment by scottmbulloch** [comment]
Confirming this is now fixed for me on 2.1.5. Thanks!
