### ISSUE TITLE
Matching ste-core not published for ste-simple-events

### ISSUE THREAD

**Issue by edzis** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#112]
## Expected Behavior
When I install latests `ste-simple-events` (2.1.2 on npm) it installs `ste-core` dependency.

## Current Behavior
Installation fails to find `ste-core@2.1.2` and asks to choose a different version.

**Comment by KeesCBakker** [comment]
@edzis, thanks for reporting. Just published version 2.1.3, this one should be OK, can you check?

**Comment by KeesCBakker** [comment]
Looks like the failing build had to do with invalid casing. On Windows-bases systems everything was fine, on Unix-based systems stuff went wrong. Should be fixed in 2.1.5.

**Comment by edzis** [comment]
Installing latest went without issues. Thanks!
