### ISSUE TITLE
Using the 'arguments' keyword crashes 'Edge dev tools'

### ISSUE THREAD

**Issue by matanshapira** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#119]
https://github.com/KeesCBakker/Strongly-Typed-Events-for-TypeScript/blob/5392bdbcfb87c06b61dfe14d9a8215ab029d37e8/packages/ste-promise-simple-events/src/PromiseSimpleEventDispatcher.ts#L46

Replacing with `[args]` solves the issue.

**Comment by KeesCBakker** [comment]
Can you check if the browser version works for you? https://www.npmjs.com/package/ste-browser

**Comment by KeesCBakker** [comment]
I'm closing the issue due to inactivity.
