### ISSUE TITLE
Transpiling issue with latest versions

### ISSUE THREAD

**Issue by sara3988** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#15]
![image](https://user-images.githubusercontent.com/19271236/36601048-6dbde4d4-18b4-11e8-8e0a-ca4a58c19a15.png)

I updated the version from 1.0.1 to the latest, and faced this issue while running some unit tests.
Looks like the issue is with transpiling : 

`Object.defineProperty(exports, "__esModule", { value: true });`
`**const** subscription_1 = __webpack_require__(4);`
`/**`
` * Base class for implementation of the dispatcher. It facilitates the subscribe`
` * and unsubscribe methods based on generic handlers. The TEventType specifies`
` * the type of event that should be exposed. Use the asEvent to expose the`
` * dispatcher as event.`
` */`
`class DispatcherBase {`
`    constructor() {`
`        this._wrap = new DispatcherWrapper(this);`
`        this._subscriptions = new Array();`
`    }`

My guess is something has changed with release version v1.1.3.
I am happy to use v1.0.1, but would be great if there is a fix for the problem I am facing with the latest versions, so I can switch to these anytime I want.

NOTE- If there is something that I need to fix on my end, just let me know!

**Comment by KeesCBakker** [comment]
Hi Sara, how are you transpiling this? Looks like const is something that's not available.

**Comment by KeesCBakker** [comment]
Just pushed a new version to NPM. Can you check if version 1.1.10 works for you?

**Comment by sara3988** [comment]
Hi Kees,
I can confirm that the v1.1.11 seems to have fixed the issue I was facing. 
Yes, my compiler options was set to target: es5, and I had issues with my tests running on phantomJS requiring ES5 only.

I can close this issue, if there is nothing else you would like investigate on this.

**Comment by KeesCBakker** [comment]
Cool! Thanks for reporting.
