### ISSUE TITLE
Exported external package typings file is not a module

### ISSUE THREAD

**Issue by stgatilov** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#2]
I have installed npm package, and now I try to use it in typescript 1.8.10:
`import events from 'strongly-typed-events';`
This gives me the following error (given that module resolution is fixed, of course):

```
Error TS2306: File 'node_modules/strongly-typed-events/StronglyTypedEvents.d.ts' is not a module.
Error TS2656: Exported external package typings file 'node_modules/strongly-typed-events/StronglyTypedEvents.d.ts' is not a module. Please contact the package author to update the package definition.
```

It seems that currently the module is not easily usable.

**Comment by daslicht** [comment]
you dont import d.ts files , you reference them : 
```
/// <reference path="node_modules/strongly-typed-events/StronglyTypedEvents.d.ts" />
```

**Comment by daslicht** [comment]
do you found any solution yet ?

**Comment by stgatilov** [comment]
Well... sort of.
I have implemented my own version =)

In fact, the implementation is rather simple, given the general idea.
And I don't need any compilcated stuff like asynchronous callbacks anyway.
As an additional bonus, I can now customize everything the way I want it (e.g. specifying method + this as callback).
