### ISSUE TITLE
Links in README as rendered by npmjs.com broken

### ISSUE THREAD

**Issue by binki** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#21]
## Expected Behavior
If I click “Check this” at [the npmjs page](https://www.npmjs.com/package/ste-signals), I should see [this page](https://github.com/KeesCBakker/Strongly-Typed-Events-for-TypeScript/blob/master/documentation/HowToUseInNodeJs.md).

## Current Behavior
When I click “Check this” at [the npmjs page](https://www.npmjs.com/package/ste-signals), I see [this 404 page](https://github.com/KeesCBakker/Strongly-Typed-Events-for-TypeScript/documentation/HowToUseInNodeJs.md).

## Possible Solution
It is possible this is an npmjs issue and needs to be raised with them. I believe they attempt to render `README.md` in a GitHub-compatible way, and this may be failing. It is also possible that the package’s `README.md` could be changed to be compatible with how npmjs renders them.

It might be a discrepancy between where the `README.md` is located in the GitHub tree compared to when it is distributed in the npmjs package. The `README.md` may be in a subdirectory of the GitHub repo, but when distributed in the npmjs package, it is treated as if it is as the root of the repo.

## Steps to Reproduce
1. https://www.npmjs.com/package/ste-signals
2. Click “Check this” or “documentation” or “examples”.

**Comment by KeesCBakker** [comment]
Great find. The problem existed in the other packages as well. Fixed them all. Thanks for reporting this issue!
