### ISSUE TITLE
How to use STE with namespace project?

### ISSUE THREAD

**Issue by JohnArcher** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#24]
I am relatively new to TypeScript, so excuse me if that is a dumb question.

My web project is build with namespaces (https://www.typescriptlang.org/docs/handbook/namespaces.html) instead of modules. I use the latest version of STE, so I updated my package.json like so and did an npm install (all fine):

```json
    "ste-core": "^1.4.3",
    "ste-events": "^1.4.3",
    "ste-signals": "^1.4.3",
    "ste-simple-events": "^1.4.3",
     "strongly-typed-events": "^1.4.3"
```

Now, with namespaces I do not use import statements, if I understand it correctly (when I try it it breaks my code). So normally I just write `var ttt = new SimpleEventDispatcher<number>();`. But the compiler tells me that it cannot find name SimpleEventDispatcher and so on.

One possibility is to declare a reference path like `///<reference path="..\node_modules\ste-simple-events\dist\index.d.ts"/>`. But this leads this error: 
`node_modules/ste-simple-events/dist/definitions.d.ts(1,69): error TS2307: Cannot find module 'ste-core'.`

I tried a test project using no namespaces but import statements and this does work. So the question is, is there a way to use it with namespace style and/or do I something wrong? Thanks a lot!

**Comment by KeesCBakker** [comment]
I've never used namespaces before. It looks like something that should be supported. If you want to use all of STE, the "strongly-typed-events": "^1.4.3" should be enough. This package references the others, so you should not have to include.

I'll have to investigate what's going on. Do you have some sample code?

**Comment by JohnArcher** [comment]
The other packages: Yeah, I already thought that, but wanted to make sure that I really have all I need. But thanks for the hint.

Here is same simple sample code:

```typescript
namespace myNamespace {
    export class MyClass {
        private _myEvent = new SimpleEventDispatcher<number>();
    }
}
```

This leads to "Cannot find name 'SimpleEventDispatcher'."

I did a little test with STE 1.0.1 where you shipped a single .d.ts file. I get it to work with namespaces, when I modify that file in the way that I delete all occurrences of the key word "export" (export `interface IEventHandler<TSender, TArgs> {` becomes `interface IEventHandler<TSender, TArgs> {`) **and** delete the complete last line (`export default StronglyTypedEventsStatic;`).

After savong these modifications (as strongly-typed-events.global.d.ts) I can "import" the definition by writing:
`///<reference path="vendor/strongly-typed-events.global.d.ts"/>`

So, I think I would need such a merged definition file. I am not sure if you can generate that automatically?

Thanks for your help anyway! Your library is very nice and helpful!

**Comment by KeesCBakker** [comment]
I'm using the following:

    import { SimpleEventDispatcher, IEvent } from 'strongly-typed-events'

    namespace myNamespace {
        export class MyClass {
            private _myEvent = new SimpleEventDispatcher<number>();

            public get MyEvent(){
                return this._myEvent.asEvent();
            }
        }
    }

My tsconfig.json looks like this:

    {
        "compileOnSave": true,
        "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "outDir": "dist",
        "declaration": true,
        "strict": true
        },
        "include": [
        "**/*.ts"
        ],
        "exclude": [
        "node_modules"
        ]
    }

I've added a zip with the info here:
[https://www.dropbox.com/s/ap9fwhyiygku8pp/STE-24.zip?dl=0](https://www.dropbox.com/s/ap9fwhyiygku8pp/STE-24.zip?dl=0)

Please let me know what I'm missing. I only installed ` "strongly-typed-events": "^1.4.3" ` in this example.

**Comment by JohnArcher** [comment]
Thanks for that!

There are two differences to my environment:
1. In tsconfig, I set module to "none", because I use no module loader. When I set it to "commonjs", the definition is recognized (but I am not sure how that would influence the build process, but that doesn't matter right now, as see point 2)
2. With "commonjs" the definition is recognized, but it breaks my other namespaces, as I write sth like `private _controller = new myNamespace.Controller.CommunicationController();` in my class definition. But this breaks the code now (which does not if I don't use the import statement). I altered your example accordingly: [STE-24.zip](https://github.com/KeesCBakker/Strongly-Typed-Events-for-TypeScript/files/1984177/STE-24.zip)

I think import with namespaces have a different meaning (aliasing), see https://www.typescriptlang.org/docs/handbook/namespaces.html ("Aliases"). Also, there seems to be a general confusion about this distinction (though the posts are  a bit old): https://github.com/Microsoft/TypeScript/issues/8004

The whole namespace stuff _and_ STE work with that one definition file I was referring to yesterday.

**Comment by KeesCBakker** [comment]
**Modules v. Namespaces**
If my understanding is correct, there are 2 things at play here: namespaces and module resolution. The zip shows that namespaces work. I think it's the way modules are resolved. When 'none' is used, it looks like an import is not allowed.

**Module**
STE is build as an external module. If my understanding is correct, the namespace is used internally:

> A note about terminology: It’s important to note that in TypeScript 1.5, the nomenclature has changed. “Internal modules” are now “namespaces”. “External modules” are now simply “modules”, as to align with ECMAScript 2015’s terminology, (namely that module X { is equivalent to the now-preferred namespace X {).

**Resolution**
I cannot find any documentation on module="none". If you are building a web application, the declare would be your best bet. With declare you basically say: "at runtime there's an object present that works like this". I'm not sure how to generate such a file in a way that won't conflict with the other systems.

Maybe you can explain a little bit more about the module="none" option? Why do you choose it? What application are you trying to build? (I spend most of my time in node-js CLI).

**Comment by JohnArcher** [comment]
Oh dear, sorry, that I keep you busy with this basic stuff (but I hope it is still interesting for you in a way). :-/

Are you sure, that namespace and import work in the zip, that **I** attached? In my tsconfig.json I set `"module": "commonjs"`, but I get this namespace error:
![screenshot_43](https://user-images.githubusercontent.com/990724/39916828-fca193d8-550b-11e8-9b61-b38304ff510a.png)

I am developing a web application (no node-js stuff). In that I have my index.html which simply `<script src="myTranspiled.js"></script>` all the transpiled js scripts (I add them manually). Somewhere I read that if you reference you js files in that classical manner you can/should set module to none (but maybe I don't remember it correctly, but it worked so far).
I would have no problem in changing to commonjs, but as I wrote above that breaks my namespaces. 

I am not sure what exactly you mean by "the declare would be your best bet", sorry. :-/ Which declare, and where?

Maybe this is helpful: I also install these typings: 
`"@types/chart.js": "^2.7.15",
"@types/gridstack": "0.0.39",
"@types/jquery": "^3.3.1",
"@types/jqueryui": "^1.12.2",
"@types/lodash": "^4.14.108",`

This works without a flaw. And if you have a look at the index.d.ts's in .e.g `node_modules\@types\chart.js` or `node_modules\@types\gridstack` you see how the definition files look that work with my setup. But unfortunately I don't know how these files where generated. :-/

**Comment by JohnArcher** [comment]
Hey there @KeesCBakker !

Any news on this? Maybe this is also interesting, as it shows a similar problem which I and others had with moment.js: https://github.com/moment/moment/issues/3763

Adding `export as namespace moment;` to the moment.d.ts helped here.

Thanks in advance!

**Comment by KeesCBakker** [comment]
Not sure how to proceed here. Maybe you can submit a PR with this behavior?

**Comment by JohnArcher** [comment]
Hey, unfortunately I don't have a glue how to achieve this, so I cannot provide a PR. :-( Sorry. I am also unsure how to proceed now. I may have a look at that soon. Thanks anyway!

**Comment by KeesCBakker** [comment]
Any new thoughts on the matter?

**Comment by JohnArcher** [comment]
Thanks for asking. Unfortunately not. :-( I am totally lost here. I think I have to live with it. It would be ok if you close this issue and we can reopen if someday I have a solution.

**Comment by KeesCBakker** [comment]
Let's see what to community does in the future.
