### ISSUE TITLE
Feature request: Get subscribers count

### ISSUE THREAD

**Issue by tzachshabtay** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#25]
Great library!
It would be useful to be able to get the number of subscriptions to an event (even better would be to get the subscriptions as a list, like in c# events: https://msdn.microsoft.com/en-us/library/system.delegate.getinvocationlist(v=vs.110).aspx).

Current workaround I'm using: `(dispatcher as any)._subscriptions.length`

**Comment by KeesCBakker** [comment]
Great. I'll look into it.

**Comment by KeesCBakker** [comment]
Hm... looks like too much impact on the code as TypeScript won't let me implement this easily.

**Comment by tzachshabtay** [comment]
What's the problem?

**Comment by KeesCBakker** [comment]
I tried to implement it with an interface, but I could not get it done. Maybe you can give it a try and submit a PR?

**Comment by andrewleader** [comment]
I'd find this useful too! I'll use tzachshabtay's workaround in the meantime, but would love something part of the library!

**Comment by KeesCBakker** [comment]
Is now fixed in 1.5.*. Please upgrade.
