### ISSUE TITLE
@Types ?

### ISSUE THREAD

**Issue by daslicht** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#3]
HI, 
I am using a Webpack based Project which uses @Types.
What is the best way to integrate Strongly-Typed-Events-for-TypeScript in such a project please?

**Comment by KeesCBakker** [comment]
I'm not sure, but the typescript d.ts is located in [StronglyTypedEvents.d.ts](https://github.com/KeesCBakker/Strongly-Typed-Events-for-TypeScript/blob/master/StronglyTypedEvents.d.ts).
