### ISSUE TITLE
Non-Uniform EventList and SimpleEventList using TArgsMap

### ISSUE THREAD

**Issue by DustinWoods** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#37]
Update (08/06): Revised the issue to focus on the issue rather than the proposed solution.

## Background
The EvenList and SimpleEventList classes are unable to assist with non uniform event arg types. If I were to create an EventList for dispatching events with different event arguments types (lets say string and number), I would need to do this:

```javascript
const myEvents = new SimpleEventList<number | string>();

events.get('event-two').subscribe((args: number | string) => {
  // Do type guard checks
});

events.get('event-one').subscribe((args: number | string) => {
  // Do type guard checks
});
```

This has several weaknesses.
1) There is no declaration which event names are associated with which event argument type.
2) When using get() to retrieve an EventDispatcher, there is no constraint of available event names (how do I know "event-one" is a valid event, but not "event-foo"?).

This makes EvenList and SimpleEventList not very useful for non-uniform event argument types. If we want to use EventList for non-uniform event types, we'll need to resort to a union or any type, giving us more work with type guards. It also is unclear what valid event names can be passed to get().

## ~Proposed structure~
Removed

## Use Cases
I think some simple examples will help explain the use cases. Let's imagine we could supply a type map to SimpleEventList that would tell the SimpleEventList which event argument types correspond to which event names.
```javascript
type MyEventsMap = {
  ['event-one']: string;
  ['event-two']: number;
};

const myEvents = new NonUniformSimpleEventList<MyEventsMap>();

events.get('event-two').subscribe((args: number) => {
  // args is definitely a number!
});

events.get('event-one').subscribe((args: string) => {
  // args is definitely a string!
});

events.get('event-one').dispatch({foo: 'bar'}) // <-- Type check error, argument {foo: 'bar'} is not compatible with string

events.get('wrong-event') // <-- Type check error, 'wrong-event' is not a key from MyEventsMap
```

Under the hood, event dispatching works exactly the same. But this interface allows us to manage a non-uniform list of dispatchers and constrain event names.

## Proposal
I'd like to get input on a couple things:

- Does this enhancement conflict with core design decisions of EventList/SimpleEventList?
- Does this feature belong in new classes, or should it replace the interface for EventList and SimpleEventList?

If this addition makes sense, I'd like to prepare a pull request. I have a few approaches I've put together that work.

Thanks for taking the time to look over this!

**Comment by DustinWoods** [comment]
Thinking on this some more - it seems less appropriate to replace existing EventList and SimpleEventList class signatures, unless there's a way to overload and default to normal behavior.

**Comment by vitaly-t** [comment]
Wouldn't life be easier with events created separately? Here's example with [sub-events](https://github.com/vitaly-t/sub-events):

```ts
const eventOne = new SubEvent<string>();
const eventTwo = new SubEvent<number>();

eventOne.subscribe((srgs: string) => {
    // args is definitely a string!
});

eventTwo.subscribe((srgs: number) => {
    // args is definitely a number!
});

eventOne.emit(123); // <-- Type check error, argument should be a string

eventTwo.emit('hello'); // <-- Type check error, argument should be a number
```

And then you can organize `[eventOne, eventTwo]` into any list you want.

**Comment by DustinWoods** [comment]
Sure, and I think this is the intended design for ste-events too. But what this doesn't cover is how the events are organized. You mention it briefly (ie "list or map"). Let me expand on your example further and show you where my proposal adds benefit.

```javascript
const eventOne = new SubEvent<string>();
const eventTwo = new SubEvent<number>();

// Organizing our events into a map
const eventMap = {
  one: eventOne,
  two: eventTwo,
};

// Proxy function for subscribing to events
function subscribe(event, fn) {
  eventMap[event].subscribe(fn);
}
```

In this example, I have a subscribe function that accepts a string for the event name, and a second argument for the callback. Nothing fancy here in terms of JavaScript. But when it comes to typings, how can we be clearer that event name "one" corresponds to a string type, and "two" to a number type? What types would you propose to use for `fn` and `event` argument?

In my proposal above, this is taken care of using Extract and index types, passing a type map as a generic. (My proposal is about typings, not the actually behavior of EventList or SimpleList)

**Comment by vitaly-t** [comment]
@DustinWoods I think that once you condense types into an array, you lose the types. TypeScript cannot revert/restore strict types from the array that way, IMO.

**Comment by DustinWoods** [comment]
Sure, Arrays have uniform type (with exception of tuples) - but we're not using arrays, using maps in this case (EventList and SimpleEventList use maps for storing key/value pairs of Dispatchers).

Hey btw thanks for taking the time to offer feedback and suggestions.

**Comment by DustinWoods** [comment]
Ping @KeesCBakker - I'd love to get your opinion on this proposal.

**Comment by vitaly-t** [comment]
@DustinWoods This is how it works in TypeScript:

```ts
const eventMap = {
    one: new SubEvent<number>(),
    two: new SubEvent<string>()
};

function event<T, K extends keyof T>(obj: T, key: K) {
    return obj[key];
}

event(eventMap, 'one').subscribe((data: number) => {

});

event(eventMap, 'two').subscribe((data: string) => {

});
```

**Comment by DustinWoods** [comment]
Yep yep @vitaly-t. This is pretty similar to how I've gone about implementing it. keyof and index types are super handy.
Just to be clear, I'm not having issues or looking for a solution, I'm proposing an enhancement to ste-events to incorporate this in a class.

**Comment by KeesCBakker** [comment]
Hey guys, thanks for the ping! The package was made to support strongly typed events. I didn't come across a non-uniform type before. I see you removed the proposal. Do we know why the generic situation does not work?

**Comment by KeesCBakker** [comment]
I first thought it was a compilation problem, but everything works:
<img src="https://i.imgur.com/luaUHJi.png"/>

The eventlist was created as a way to store multiple events for a single object, not as a way to _expose_ events. Events should always be exposed by the event, and here is were I have a problem:
<img src="https://i.imgur.com/voHw0R6.png" />

So it looks like we need to find a different way of exposing the event on the object.

**Comment by DustinWoods** [comment]
Thanks for chiming in @KeesCBakker. Yeah, to clarify there's no issue with the code I posted above (with number | string). That was to show how EventList with a union types has drawbacks.

Also I did not consider the asEvent() method :thinking: 

@KeesCBakker would you have time to look at a rough merge request and see how I propose this could be implemented?

**Comment by DustinWoods** [comment]
I put together an a working pull request: #42 
This might help explain the functionality I'm proposing to add. It works great for my use cases, maybe others might benefit from it as well?

**Comment by vitaly-t** [comment]
@DustinWoods The idea of using events via strings made me [highlight it in my own module](https://github.com/vitaly-t/sub-events/wiki/Event-List). Cheers!

**Comment by KeesCBakker** [comment]
I've merged your pull request, implemented a `NonUniformSimpleEventList` based on your code and added some documentation: https://github.com/KeesCBakker/Strongly-Typed-Events-for-TypeScript/blob/master/documentation/HowToAddMultipleEventsToAClass.md#non-uniform-event-lists. The feature has been pushed to NPM under 1.6. Thanks for your contribution @DustinWoods. Thanks @vitaly-t for participating in the discussion.

**Comment by DustinWoods** [comment]
Thanks @KeesCBakker glad you found this addition valuable!

@vitaly-t I'll give sub-events a look over. Glad the discussion helped you out.
