### ISSUE TITLE
Add dispose method

### ISSUE THREAD

**Issue by avber** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#4]
Hi,

could you add dispose/clear method to clear all subscriptions?

It will be useful for scenarios where objects are created and destroyed frequently.

Thanks

**Comment by KeesCBakker** [comment]
I'll look into it!

**Comment by KeesCBakker** [comment]
I'll add it to the next version.

**Comment by KeesCBakker** [comment]
Added a clear method to clear all subscriptions to a dispatcher.
