### ISSUE TITLE
Unsubbing bound method doesn't work

### ISSUE THREAD

**Issue by xFahdonx** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#45]
Trying to unsub a bound method from a SignalDispatcher. No unsubbing is finding the place.

## Expected Behavior
I tried subscribing to an event with a bound method to access a class like this:

```
let onUpdate = new SignalDispatcher = new SignalDispatcher();
let component = new Component();
onUpdate.sub(component.Update.bind(component));

void Update(){
 this.onUpdate.dispatch();
}

class Component {
 public Update(){
  //do stuff
 }
}
```

## Current Behavior
However, when I try to unsubscribe from the event with the same method, It won't subscribe. Removing the bind works however but then I can't access 'this' in the component.

## Context (Environment)
I'm trying to create an entity-component-based Engine. For the main loops, I want to use this event system.

**Comment by KeesCBakker** [comment]
I'm not sure what you are trying to do. I could not get the example to compile, is this what you are trying to do: https://repl.it/repls/SpanishPointlessScientist

```const { SignalDispatcher } = require("strongly-typed-events")

class Component {
 Update(){
  console.log("update received");
 }
}

let onUpdate = new SignalDispatcher();
let component = new Component();
onUpdate.sub(component.Update.bind(component));

function Update(){
 onUpdate.dispatch();
}

Update();
```

**Comment by KeesCBakker** [comment]
The main problem is that the `component.Update.bind(component)` will generate a reference that cannot be know by the class. It doesn't "know" it, so it cannot unsubscribe to it. It needs to know how it was called in order for it to unsubscribe, but I think this goes agains OO priciples; something like this will work:

```const { SignalDispatcher } = require("strongly-typed-events")
let onUpdate = new SignalDispatcher();
let method = null;

class Component {

  constructor(){
    this.name = "Kaas";
  }

 Update(){
  console.log("update received for " + this.name);
  onUpdate.unsub(method);
 }
}

let component = new Component();
method = component.Update.bind(component);
onUpdate.sub(method);

function Update(){
 onUpdate.dispatch();
}

// Should trigger something
Update();
// Should not trigger something
Update();```

My main question would be: why does is the event (dispatcher) not part of the class?

**Comment by KeesCBakker** [comment]
What if the whole class is agnostic to the event?

```javascript
const { SignalDispatcher } = require("strongly-typed-events")
let onUpdate = new SignalDispatcher();

class Component {

  constructor(){
    this.name = "Kaas";
  }

 Update(){
  console.log("update received for " + this.name);
 }
}


let component = new Component();
let method = () => {
  component.Update();
  onUpdate.unsub(method);
};
onUpdate.sub(method);

function Update(){
 onUpdate.dispatch();
}

// Should trigger something
Update();
// Should not trigger something
Update();
```

**Comment by xFahdonx** [comment]
Right so let me explain al little more what I'm trying to do. The code I first posted is just a small example but it looking back to it, it does not explain what I'm trying to do.

So I have 2 classes. A main App class with components as an array. In this App, I have 3 loops called Awake, Start and Update. These are events. components inside the app subscribe to all the loops with there own Awake, Start and Update Method. To access the properties inside the component, I need to bind the component to the method. A bit like this:

`
import { SignalDispatcher } from "strongly-typed-events";

class App {
  private components: Component[] = [];
  private onUpdate = new SignalDispatcher();
  constructor() {}

  AddComponent(component: Component) {
    this.components.push(component);
    this.onUpdate.sub(component.Update.bind(component));
  }

  Update() {}
}

class Component {
  private name = "component";
  constructor() {}

  Update() {
    this.onUpdate.dispatch();
  }
}

let app = new App();
let component = new Component();

app.AddComponent(component);
app.Update;
`

This works but what if I want to remove the component? removing it from the array is easy but if I don't unsub from the event. the method is still called so let's just do that then. 

`
import { SignalDispatcher } from "strongly-typed-events";

class App {
  private components: Component[] = [];
  private onUpdate = new SignalDispatcher();
  constructor() {}

  AddComponent(component: Component) {
    component.Id = this.components.length;
    this.components.push(component);
    this.onUpdate.sub(component.Update.bind(component));
  }

  RemoveComponent(component: Component) {
    this.onUpdate.unsub(component.Update);
    // this.onUpdate.unsub(component.Update.bind(component)); doesn't work either
    delete this.components[component.Id];
    this.components.length--;
  }

  Update() {
    this.onUpdate.dispatch();
  }
}

class Component {
  private name = "component";
  public Id = -1;
  constructor() {}

  Update() {
    console.log(this.name);
  }
}

let app = new App();
let component = new Component();

app.AddComponent(component);
app.Update();
app.RemoveComponent(component);
app.Update();
`

It removes the component from the array but does not unsubscribe, This is essentially what I'm trying to do. My Update method is, of course, called every frame. instead of a handful of times.

I hope this helps.

**Comment by KeesCBakker** [comment]
Ah, that example helps a lot. I've looked at it, and the main problem is knowing which object is connected to which handler. When I do the following, I created something that works.

```typescript
import { SignalDispatcher } from "strongly-typed-events";

class App {
  private components: Component[] = [];
  private events: (()=>void)[] = [];

  private onUpdate = new SignalDispatcher();
  constructor() {}

  AddComponent(component: Component) {
    component.Id = this.components.length;
    var event = () => component.Update();
    
    this.components.push(component);
    this.events.push(event);
    this.onUpdate.sub(event);
  }

  RemoveComponent(component: Component) {

    let event = this.events[component.Id];
    this.onUpdate.unsub(event);

    delete this.components[component.Id];
    delete this.events[component.Id];

    this.components.length--;
  }

  Update() {
    this.onUpdate.dispatch();
  }
}

class Component {
  private name = "component";
  public Id = -1;
  constructor() {}

  Update() {
    console.log(this.name + ": " + this.Id);
  }
}

let app = new App();
let component0 = new Component();
let component1 = new Component();

app.AddComponent(component0);
app.AddComponent(component1);
// expect log of 0 and 1
app.Update();

app.RemoveComponent(component0);

// expect log of 1
app.Update();
```
Is this something that helps in your case? Or do you think the library should support your usecase better?

**Comment by KeesCBakker** [comment]
I'm closing the issue due to inactivity.
