### ISSUE TITLE
Feature request: Make events cancellable

### ISSUE THREAD

**Issue by sionzeecz** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#48]
Sometimes a "third-party" developer wants to cancel some task. Imagine an event of a data change where developer wants to abort the change. He should be able to call eventManagement.cancel() where the dispatch function at event should return boolean if event was cancelled.

Of-course this should be possible only in "pre-events" or developer makes undo action when `event.isCancelled()`.

## Possible Solution

1.) Change dispatch's return type to boolean 
2.) Add cancel() and isCancelled() to **IEventManagement** or add ability to set custom EventManagement and link it inside events.

## Context (Environment)

I'm developing WYSIWYG editor and I want to make it flexible as is it possible. In my project I'm using strongly-typed-events everywhere but this is the last puzzle what I am missing to have great result. If you are not able to modify existing functions then could you add something like: `dispatchCancellable`? 

## Possible Implementation
An example on Car class
```typescript
class Car {
  private health: number = 10;
  private _onCarDestroy: EventDispatcher<Car, any> = new EventDispatcher<Car, any>();

  onCarDestroy(): IEvent<Car, any> { return this._onCarDestroy.asEvent() }

  destroyCar(): void {
    const result = this._onCarDestroy.dispatch(this) // or this._onCarDestroy.dispatchCancellable(this)

    // with "EventStatus" enum
    if(result === EventStatus.OK) {
      this.health = 0;
    }

    // with boolean solution
   if(result) {
      this.health = 0;
   }
  }
}

const car = new Car();
car.onCarDestroy.subsribe((car, _, eventManagement) => {
  if(car.isAdmin()) { // or any other variable not related to car instance
    eventManagement.cancel(); // makes `result` above "false" or "EventStatus.Cancelled"
  }
})

```

---

Sure I can do something like:
```javascript
const eventArgs = {_cancelled: false, cancel() => {...})
event.dispatch(eventArgs);
if(eventArgs._cancelled) ....
```

but why developer should find "unsub" and "stopPropagation" in different argument than cancel function. It will make the project a little bit messy. 

Having an ability to adjust EventManagement instance will be enough.

**Comment by KeesCBakker** [comment]
This is quite a feature to be able to cancel events. I need to give it some extra thought, as it should not break anything. 

I'm not sure if it is wise to provide a whole new `eventManagement` object. 

The current events have no base class. I could introduce an interface for this. 

🤔

**Comment by KeesCBakker** [comment]
I have a `stopPropagation()`, would that work for you?

```
  let dispatcher = new SignalDispatcher();

  let a = 0;
  dispatcher.sub(ev => {
    a++;
    if (a > 2) {
      ev.stopPropagation();
    }
  });

  let b = 0;
  dispatcher.sub(() => {
    b++;
  });

  dispatcher.dispatch();
  dispatcher.dispatch();
  dispatcher.dispatch();
  dispatcher.dispatch();

  expect(a).to.eq(4, "A should be 4, because 4 dispatches are done.");

  expect(b).to.eq(
    2,
    "B should be 2, because everything after the 2nd dispatch is cancelled."
  );
```

**Comment by KeesCBakker** [comment]
Version 2.0 should return the status to your dispatch. The reason I do not call it cancel is because the event might have been handled by previous handlers. `dispatch` will return an IPropagationStatus with a `propagationStopped` boolean. When a `dispatchAsync` is done, no status is returned, because those events are fire and forget events triggered by a timeout.

This is what will come back: https://github.com/KeesCBakker/Strongly-Typed-Events-for-TypeScript/blob/v2.0/packages/ste-core/src/dispatching/IPropagationStatus.ts

**Comment by KeesCBakker** [comment]
Also working on event handlers with a Promise implementation. Those will be stoppable as well, which might interest some. Check: https://github.com/KeesCBakker/Strongly-Typed-Events-for-TypeScript/blob/v2.0/packages/ste-promise-events/src/PromiseEventDispatcher.ts

**Comment by KeesCBakker** [comment]
Closing the issue. Version 2.0 is now released and with it you should be able to implement your use case.
