### ISSUE TITLE
Handle event in Stencil app

### ISSUE THREAD

**Issue by TakhirMamirov** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#57]
I have a Stencil app with several pages. One page shall be notified and reload if something happens on another page. How can I listen for signal event on another page?

**Comment by KeesCBakker** [comment]
Sorry, I have no familiarity with Stencil apps.

**Comment by KeesCBakker** [comment]
Closing the issue. Please let me know if you have further details.
