### ISSUE TITLE
Cannot read property 'DispatcherBase' of undefined

### ISSUE THREAD

**Issue by michelevirgilio** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#58]
I'm trying to use ste-browser package, but by writing this html i get the error in the title:

```
<!DOCTYPE html>
<html>
    <head>
        <script src="https://cdn.jsdelivr.net/npm/ste-browser/dist/ste-simple-events.js"></script>
    </head>
    <body>
        aaa
    </body>
</html>
```
maybe i'm missing something or the documentation needs some integrations?
Thanks

**Comment by KeesCBakker** [comment]
The docs state the following:

Include the script from this NPM package or from a CDN:
```html
<script src="https://cdn.jsdelivr.net/npm/ste-browser@latest/dist/strongly-typed-events.js"></script>
```
The following test still works on my machine: https://github.com/KeesCBakker/Strongly-Typed-Events-for-TypeScript/blob/master/packages/ste-browser/test/clock.html

**Comment by michelevirgilio** [comment]
Hi, thank you for your reply.
So i need to use the whole strongly-typed-events.js, if i would to use only simple events is it possible?

**Comment by KeesCBakker** [comment]
Currently that's the only one that's possible, but I will check if I can make all versions "browserfied".

**Comment by KeesCBakker** [comment]
Please check if the latest release works for you: https://www.npmjs.com/package/ste-browser

**Comment by KeesCBakker** [comment]
Should now work with the latest version:

```html
<script src="https://cdn.jsdelivr.net/npm/ste-browser@latest/dist/ste-events.js"></script>
<script src="https://cdn.jsdelivr.net/npm/ste-browser@latest/dist/ste-events.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/ste-browser@latest/dist/ste-simple-events.js"></script>
<script src="https://cdn.jsdelivr.net/npm/ste-browser@latest/dist/ste-simple-events.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/ste-browser@latest/dist/ste-signals.js"></script>
<script src="https://cdn.jsdelivr.net/npm/ste-browser@latest/dist/ste-signals.min.js"></script>
```

**Comment by michelevirgilio** [comment]
Thank you, the error is gone!
