### ISSUE TITLE
Unsubscribe during dispatching Events

### ISSUE THREAD

**Issue by KmaxKmax** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#9]
Hi, I faced problem during dispatching events. I have few objects, that are subscribed for target object update. When the target object is updated the dispatcher is going through the array of subscribers and runs their reactiong routines. But my app logic in those reaction routines could decide to unsubscribe. The unsubscription goes well, but it is directly affecting the subscription array during the dispatching events to other subscribers. 
For example I have 2 subscribers. First is informed and his reaction routine unsubscribe it from the subscription array. Then there should be second round for dispatcher to inform second subscriber, but the length of the subscription array is suddenly only 1 and because of that the FOR routine in dispatcher will never try to reach the second subscriber.
I have resolved this with copying the subscription array and dispatching events from copy, which is not affected from original which is changed via unsubscribing by listener. Like this:
```
protected _dispatch(executeAsync: boolean, scope: any, args: IArguments): void {
            let copy = new Array<Subscription<TEventHandler>>();
            copy = this._subscriptions.slice();
            for (let i = 0; i < copy.length; i++) {
                let sub = copy[i];
             ...
```

Another solution could be, to set some lock for the subscription array, and let the unsubscribing routine to wait, until the lock will be set off.

I hope it is understandable, because it is quite complicated to explain even in my mother language :)

**Comment by KeesCBakker** [comment]
The projects uses unit testing. Could you create a fork with a unit test to mimic this behavior?

**Comment by KeesCBakker** [comment]
Makes it a bit easier to debug.

**Comment by KeesCBakker** [comment]
I think the following code will help you and I'll be adding it soon:
```  
  protected _dispatch(
    executeAsync: boolean,
    scope: any,
    args: IArguments
  ): void {
    this._subscriptions
      .filter(sub => !sub.isOnce || !sub.isExecuted)
      .forEach(sub => sub.execute(executeAsync, scope, args));
  }
```

**Comment by KeesCBakker** [comment]
This bug is fixed by the latest commits.
